## Karşılaştırma Operatörleri

### Sayısal Karşılaştırmalar

In [1]:
2 < 3

True

In [2]:
3 <= 3

True

In [3]:
2 == 3

False

In [4]:
2 <= 3

True

In [5]:
x, y = 2, 3
x < y

True

### Diğer Karşılaştırmalar

In [6]:
"carl" < "chris" 

True

In [7]:
3 < "chris"

TypeError: '<' not supported between instances of 'int' and 'str'

In [8]:
3 < 4.1

True

In [9]:
import numpy as np
np_boy = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_kilo = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bke = np_kilo / np_boy ** 2
bke

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [10]:
bke > 23

array([False, False, False,  True, False])

## Mantıksal Operatörler

In [11]:
# Ve Operatörü
print(True and True)
print(True and False)
print(False and True)
print(False and False)

True
False
False
False


In [12]:
x = 12
x > 5 and x < 15

True

In [13]:
# Veya Operatörü
print(True or True)
print(True or False)
print(False or True)
print(False or False)

True
True
True
False


In [14]:
y = 5
y < 7 or y > 13

True

In [15]:
# Değil Operatörü
print(not True)
print(not False)

False
True


### Mantıksal Operatörün NumPy'da Kullanımı

In [16]:
bke > 21

array([ True, False,  True,  True,  True])

In [17]:
bke < 22

array([ True,  True,  True, False,  True])

In [18]:
bke > 21 and bke < 22

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Mantıksal operatörleri NumPy üzerinde kullanmak için aşağıdaki metotlar kullanılır:

- `logical_and()`
- `logical_or()`
- `logical_not()`

In [19]:
np.logical_and(bke > 21, bke < 22)

array([ True, False,  True, False,  True])

In [20]:
bke[np.logical_and(bke > 21, bke < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## if, elif, else

In [21]:
z = 4
if z % 2 == 0 :
    print("z çifttir")

z çifttir


In [22]:
z = 5
if z % 2 == 0 :
    print("z çifttir")

In [23]:
z = 5
if z % 2 == 0 :
    print("z çifttir")
else:
    print("z tektir")

z tektir


In [24]:
z = 3
if z % 2 == 0 :
    print("z 2'ye tam bölünür") # Yanlış
elif z % 3 == 0 :
    print("z 3'e tam bölünür") # Doğru
else :
    print("z 2'ye de 3'e de bölünmez")

z 3'e tam bölünür


In [25]:
z = 6
if z % 2 == 0 :
    print("z 2'ye tam bölünür") # Doğru
elif z % 3 == 0 :
    print("z 3'e tam bölünür") # Hiç sormaz
else :
    print("z 2'ye de 3'e de bölünmez")

z 2'ye tam bölünür


## Pandas Veri Çerçevelerini Filtreleme 

In [26]:
import pandas as pd
brics = pd.read_csv('data\\brics.csv', index_col=0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [27]:
# Alanı 8 Milyon km^2'den büyük şehirleri seçelim.
brics.loc[brics['area'] > 8, 'country']

BR    Brazil
RU    Russia
CH     China
Name: country, dtype: object

In [28]:
# Alanı 8 Milyon km^2'den büyük 10 Milyon km^2'den küçük şehirleri seçelim.
import numpy as np
brics.loc[np.logical_and(brics['area'] > 8, brics['area'] < 10), 'country']

BR    Brazil
CH     China
Name: country, dtype: object